### ISSUE TITLE
Is the deps.edn example correct?

### ISSUE THREAD

**Issue by pyrmont** [thiru/repl-base#1]
In the README, it suggests adding the following to your `deps.edn` file:

```clj
thiru/repl-base {:git/url "https://github.com/thiru/clj-reloader"
                 :sha "<COMMIT SHA>"}
```

Is the URL meant to be `thiru/clj-reloader`? If so, what's the relationship between this and [that repo](https://github.com/thiru/clj-reloader)?

**Comment by thiru** [comment]
Oh, that's just a typo.  Thanks for catching that (fixed now).

There is no real relation between these two repos.
